### ISSUE TITLE
KeyError: 'request_id'

### ISSUE THREAD

**Issue by Elawphant** [hishnash/djangochannelsrestframework#34]
**I am getting KeyError: 'request_id'**
I don't know this is an issue or I am doing something wrong. If I am doing something wrong, please point me a correction.

**Consumer:**
```
class MessageConsumer(ListModelMixin, PatchModelMixin, UpdateModelMixin, DeleteModelMixin, GenericAsyncAPIConsumer):
    '''A Consumer for Notifications'''

    queryset = models.Message.objects.all()
    serializer_class = serializers.MessageSerializer

    def get_queryset(self):
        return models.Message.objects.filter(record__in=models.Record.objects.filter(user=self.request.user)).order_by('-message_date_created')
```

**Routing:**
```
websocket_urlpatterns = [
    path('message', consumers.MessageConsumer),
]
```

**Serializer:**
```
class MessageSerializer(serializers.ModelSerializer):
    '''Serializer for Notification'''
    message_date_created = serializers.DateTimeField(required = False, format="%Y-%m-%d", read_only=True)

    class Meta:
        model = models.Message
        fields = [
            'record',
            'message_title', 
            'message_date_created',
            'message_status',
        ]
```

**My request is, e.g.:**
```
{"stream":"message","payload":{"action":"list","data":{},"request_id":"56def654-9087-45f8-9f12-7a7f6c78b04d"}}
```

**I am receiving the following error:**

```
WebSocket HANDSHAKING /message [127.0.0.1:56054]
WebSocket CONNECT /message [127.0.0.1:56054]
Exception inside application: 'request_id'
Traceback (most recent call last):
  File "/.../python3.8/site-packages/channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "/.../python3.8/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/.../python3.8/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/.../python3.8/site-packages/channels/generic/websocket.py", line 196, in websocket_receive
    await self.receive(text_data=message["text"])
  File "/.../python3.8/site-packages/channels/generic/websocket.py", line 259, in receive
    await self.receive_json(await self.decode_json(text_data), **kwargs)
  File "/.../python3.8/site-packages/djangochannelsrestframework/consumers.py", line 158, in receive_json
    request_id = content.pop("request_id")
KeyError: 'request_id'
WebSocket DISCONNECT /message [127.0.0.1:56054]
```

**Comment by Elawphant** [comment]
Update:
I was using a serializer from drf json api, instead of drf. changing serializer to drf resolved the issue
