### ISSUE TITLE
[BUG] Error while subscribing to a model

### ISSUE THREAD

**Issue by romulo-dbts** [hishnash/djangochannelsrestframework#38]
Hi, first of all, I am trying your lib for the very first time and it seems really handy. Probably my issue it is just a miss configuration. I would be more then happy to help improving the documentation for this case. 

**Describe the bug**
I am basically giving a try, so I just copied and pasted some piece of code from the documentation but it is not working properly, giving me a 500 (Server Internal error) while subscribing to an action.

**To Reproduce**
`views.py`
```
class TestConsumer(ObserverModelInstanceMixin):
    queryset = get_user_model().objects.all()
    serializer_class = UserSerializer
```

`urls.py`
```
urlpatterns = [
    re_path(r'', include(router.urls)),
    re_path('ws', TestConsumer)
]
```

`Request`
```
{
    "action": "subscribe_instance",
    "pk": 42,  
    "request_id": 4 
}
```

**LOG**
`Error`
```
Traceback (most recent call last):
  File "/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "lib/python3.8/site-packages/djangochannelsrestframework/observer/generics.py", line 64, in __init__
    super().__init__(*args, **kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

 - OS: Ubuntu 
 - Version 20.04
 - Python 3.8
 - djangorestframework==3.11.0
 - django==3.0.4

**Comment by romulo-dbts** [comment]
I went deeper in the problem and it breaks while calling __init__ from https://github.com/django/channels/blob/master/channels/consumer.py#L37

The variables at some point are:
```
> lib/python3.8/site-packages/channels/generic/websocket.py(160)__init__()
    159         import ipdb; ipdb.set_trace()
--> 160         super().__init__(*args, **kwargs)
    161         if self.groups is None:

ipdb> args                                                                                                                                                                       
self = <authentication.views.MyConsumer object at 0x7f10fcd7f970>
args = (<WSGIRequest: GET '/v2/ws/'>, None)
```

**Comment by romulo-dbts** [comment]
At the end of the day I could manage the problem. Actually I have skipped all the setup/configuration for Django channels. This was the first time that I used this framework and I missed have a brief mention to that setup in the documentation. Would  be good writing a paragraph about that?
