### ISSUE TITLE
Exception TypeError: has_permission() got an unexpected keyword argument 'scope'

### ISSUE THREAD

**Issue by makiolo** [hishnash/djangochannelsrestframework#52]
Maybe not is a bug. I am testing this library, but have problems.
This exception appear when try since my websocket client send json: {'action': 'list', 'request_id': 18}

**To Reproduce**
My model is very simple. I am testing:

```
class Stock(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=128)
    price = models.FloatField()
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "stock"
        verbose_name_plural = "stocks"
        ordering = ['-id', ]

    def __str__(self):
        return self.name
```

And this is the restconsumer:

```
from djangochannelsrestframework.mixins import ListModelMixin


class StockConsumer(ListModelMixin, GenericAsyncAPIConsumer):
    queryset = Stock.objects.all()
    serializer_class = StockSerializer
    permission_classes = (permissions.IsAuthenticated,)
```

And serializer is a standart ModelSerializer.

My websocket client (from javascript) do this:
```
<script>
let socket = new WebSocket('ws://localhost:8000/ws/stock/');
let timer = null;
socket.onopen = () => {
    timer = setInterval(() => {

        request = {
            "action": "list",
            "request_id": 18
        }

        socket.send(JSON.stringify(request));

    }, 1000);
};
socket.onclose = socket.onerror = () => {
    clearInterval(timer);
};
socket.onmessage = function(event) {
  var pMsg = document.getElementById("id123");
  if(pMsg == null)
  {
      let pMsg = document.createElement("p")
      pMsg.id = "id123"
      document.body.appendChild(pMsg)
  }
  pMsg.innerHTML = event.data
}
</script>
```

**LOG**
```
127.0.0.1:55509 - - [01/Feb/2021:21:05:00] "WSCONNECT /ws/stock/" - -
2021-02-01 21:05:01,958 ERROR    Exception inside application: has_permission() got an unexpected keyword argument 'scope'
Traceback (most recent call last):
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\channels\sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\channels\auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\channels\consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\channels\utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\channels\consumer.py", line 73, in dispatch
    await handler(message)
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\channels\generic\websocket.py", line 196, in websocket_receive
    await self.receive(text_data=message["text"])
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\channels\generic\websocket.py", line 259, in receive
    await self.receive_json(await self.decode_json(text_data), **kwargs)
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\djangochannelsrestframework\consumers.py", line 198, in receive_json
    await self.handle_action(action, request_id=request_id, **content)
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\djangochannelsrestframework\consumers.py", line 217, in handle_action
    await self.handle_exception(exc, action=action, request_id=request_id)
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\djangochannelsrestframework\consumers.py", line 117, in handle_exception
    raise exc
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\djangochannelsrestframework\consumers.py", line 205, in handle_action
    await self.check_permissions(action, **kwargs)
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\djangochannelsrestframework\consumers.py", line 93, in check_permissions
    if not await ensure_async(permission.has_permission)(
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\asgiref\sync.py", line 296, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "c:\programdata\miniconda3\envs\django_test\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "c:\programdata\miniconda3\envs\django_test\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "c:\programdata\miniconda3\envs\django_test\lib\site-packages\asgiref\sync.py", line 334, in thread_handler
    return func(*args, **kwargs)
TypeError: has_permission() got an unexpected keyword argument 'scope'
127.0.0.1:55509 - - [01/Feb/2021:21:05:01] "WSDISCONNECT /ws/stock/" - -
```

 - OS: Windows 10
```
Packages related:
django-rest-auth            0.9.5
djangochannelsrestframework 0.2.1
djangorestframework         3.12.2
djangorestframework-gis     0.15
```

**Comment by hishnash** [comment]
From where are you importing `permissions.IsAuthenticated` is it possible this is importing the DRF version rather than the version provided by this package? 

`from djangochannelsrestframework import permissions`

**Comment by makiolo** [comment]
yeah, my import is correct.

I try also with AllowAny and I have the same error.
